### PR TITLE
DISREGARD PREVIOUS CHANGES - approve this one!

### PR DESCRIPTION
**Pull request by selectusamicah**
This is the correct version of the updates to the database.

### CODE REVIEW

**Comment by ajsingh273** [comment]
@selectusamicah These changes look good. On the last record, can you remove the comma: https://github.com/selectusamicah/federal-incentives/blob/712f15c225709d723313f1405f9e557c9d8f2bb0/articles.js#L1742

Then I will merge.

**Comment by selectusamicah** [comment]
I'm not seeing the comma - it appears to already be gone

**Comment by ajsingh273** [comment]
@selectusamicah Its still there on your end. Look here: https://raw.githubusercontent.com/selectusamicah/federal-incentives/712f15c225709d723313f1405f9e557c9d8f2bb0/articles.js

**Comment by selectusamicah** [comment]
Alright - I think I did.

**Pull request merged**
